import smtplib
from email.mime.text import MIMEText

port = 587
smtp_server = "smtp.gmail.com"
login = "kbhiteam@gmail.com"  # Your login generated by Mailtrap
password = "hrlkynudtcmfhreb"  # Your password generated by Mailtrap

sender_email = "kbhiteam@gmail.com"
receiver_email = "kadir@kontent.com.tr"

# Plain text content
text = "Doğum Günü Cronu Arıza Vermeye Başladı"

# Create MIMEText object
message = MIMEText(text, "plain")
message["Subject"] = "Doğum Günü Video Oluşturucusu"
message["From"] = sender_email
message["To"] = receiver_email

# Send the email
with smtplib.SMTP(smtp_server, port) as server:
    server.starttls()  # Secure the connection
    server.login(login, password)
    server.sendmail(sender_email, receiver_email, message.as_string())

print('Sent')