title_svg: title.svg
date_svg: date.svg
script_title : 'Selam {title}.'
script_date  : 'Bugün {date}.'
script1 : 'Yeni Bir Gün İçin Güneş Doğdu, Seninle Birlikte Yükseliyor ve Parlıyor!'
script2 : 'Hayatın Sana Mutluluk ve Başarılar Getirmesini Dileriz.'
script3 : 'Doğum Günün Kutlu Olsun!'
